AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Lambda function to compress image by converting it into Webp'

Resources:
  CompressImage:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: post
